### ISSUE TITLE
Documentation should reflect expected usage

### ISSUE THREAD

**Issue by eurochriskelly** [marklogic/marklogic-data-hub#1075]
#### The issue

Documentation provides examples with XML content samples and no description of how to handle attachments. 

More complete examples of how content can be either a map/json:object or a node

#### Tech details

MarkLogic 9.0.5 / Non quickstart

**Comment by kcoleman-marklogic** [comment]
@eurochriskelly Can you provide a little more context? 

Are you talking about the discussion of the envelope pattern here? 

When you say "how to handle attachments", are you referring to application-specific attachments rather than the attachment DHF generates from the source data? Handle attachments while doing what?

**Comment by eurochriskelly** [comment]
Hi, Kim,

Sorry for the delay. I'm talking about DHF in general (version 3/ML 9-0.5). The documentation provides examples with xml content. None of the samples show how to handle attachments. From the source and from other discussions it seems the "right" way to use DHF is with maps (or json:objects) for passing the data around. 

 So the standard DHF envelope pattern where the attachment is the instance in STAGING database and then gets loaded into the <attachments/> element in the FINAL database does not happen when using the code samples in the documentation (https://marklogic.github.io/marklogic-data-hub/docs/server-side/) don't attach the attachment. This is also true of code generated using DHF gradle
