### ISSUE TITLE
Need info on requests that get fired when selecting a map

### ISSUE THREAD

**Issue by bsrikan** [marklogic/marklogic-data-hub#1169]
####QUESTION
Short description :
When a map is selected, there are 7 requests that get fired. Is this expected. Can you please explain what do these requests have to do with loading a saved map:

```
Request name          Type                 URL
entities              GET         http://localhost:8080/api/current-project/entities/
search                POST        http://localhost:8080/api/search
<mapName_selected>    GET         http://localhost:8080/api/current-project/mappings/prodMap3
search                POST        http://localhost:8080/api/search
search                POST        http://localhost:8080/api/search
mappings              GET         http://localhost:8080/api/current-project/mappings
doc?database=....     GET         http://localhost:8080/api/search/doc?database=STAGING&docUri=%2Fproducts%2Fboard_games_accessories.csv-0-10

```
This is in latest develop as of Jul 12 2018.

Subscribing QA: @ayuwono @rahulvudutala

**Comment by wooldridge** [comment]
Thanks, @bsrikan. Now that we're loading mapping information via routing as a child view on the mapping page, some of these calls are probably superfluous.

```
entities              GET  --> Get all defined entities for populating the side nav
search                POST --> Get source docs summary for the entity associated with the selected mapping (need a sample URI)
<mapName_selected>    GET --> Get the selected map
search                POST  --> Probably an unnecessary duplicate of above
search                POST  --> Probably an unnecessary duplicate of above
mappings              GET  --> Get all mappings for populating the left nav
doc?database=....     GET  --> Get the source document content based on the URI retrieved above
```

- The first can probably be skipped after the first page load since we're now loading a new mapping as a child view and don't need to reload the side nav.
- The second can be skipped if a mapping has a defined URI (see #1163). 
- The extra search POSTs can probably be skipped.

Addressing this is a lower priority than bug fixes.

**Comment by aebadirad** [comment]
Since this has been explained, closing the issue. We can discuss better ways to make calls as part of a story.
