### ISSUE TITLE
RFE: Make URI source collection configurable in harmonization flows

### ISSUE THREAD

**Issue by kcoleman-marklogic** [marklogic/marklogic-data-hub#1190]
Suppose you want to harmonize entities of the same entity type from different sources. I have 2 input flows, 2 mappings, 2 harmonization flows. The default collector plugin uses `options.entity` as the name of the collection from which to gather URIs, which does not support this use case.

In a multi-source scenario, I want to use some input batch specific collection name as the URI source. To do so today, I must modify the collector plugin for each flow to either hard code a different collection name or set the collection name via an option and modify the collector plugin to use `options.myOptionName`.

This all works fine, but strikes me as a design flaw: I expect that creating entity instances for the same type from multiple input sources is not an edge case in data integration.

If the harmonization flow creation enabled you to specify a URI source collection name, it could default to the entity type name, but be overridable by the flow creator without modifying the collector plugin code.

**Comment by kcoleman-marklogic** [comment]
I should probably take a step back and say that the basic desire is to be able to create harmonized entities of the same entity type from two different sources. Period. e.g. I define a single Product entity, and now I want to create Product instances from raw data coming from two different sources. Said data may be "shaped" differently. It shouldn't matter, as long as I can specify how to extract the entity properties from each.

You can see this use case already in the Product data that QS uses, albeit in a somewhat contrived way. Some of input data has a field named "sku" and some of it has a field named "SKU". I had to split the input documents into separate folders in 4.0.0 because the model-to-model mapping couldn't (yet) accommodate that kind of difference.

The reason I brought up the collections is because we are really close to being able to support the use case already. I believe what prevents us from doing so is that, though I can direct my raw data into a given collection when I ingest, I cannot direct the harmonization flow to draw its input from that collection without the hacking I mentioned in the original description. The harmonization flow always wants to use the entity name as the input source collection.

However, that's implementation, which I should not be dictating.  :) You guys may have a better way of achieving the desired end outcome.

**Comment by grechaw** [comment]
definitely a shortcoming of current design, and as for our knowing better, bah I say to that, bah!

**Comment by wooldridge** [comment]
Thanks for the detailed explanation, @kcoleman-marklogic. Seems like there are many ways to skin this cat. Thinking out loud here, let's say:

Source Data 1 has "sku" property.
Source Data 2 has "SKU" property.
Canonical Product entity has "sku" property.

We want to harmonize both data sources into the single Product entity. 

Current method (not hacking code):

1. Load Source Data 1 associated with Product entity.
2. Load Source Data 2 associated with Product entity.
3. Create Mapping 1 for "sku" -> "sku".
4. Create Mapping 2 for "SKU" -> "sku".
5. Create Harmonization Flow 1 with Mapping 1.
6. Create Harmonization Flow 2 with Mapping 2.
7. Run Harmonization Flow 1.
8. Run Harmonization Flow 2.

As Kim describes, the above runs each harmonization flow against all the loaded data , which is a waste. As Kim also describes, it would be nice to be able to specify that a harmonization flow (or perhaps a mapping) be associated with a particular input subset without having to write code. So then you could have:

7. Run Harmonization Flow 1 against Source Data 1.
8. Run Harmonization Flow 2 against Source Data 2.

Another way to do this (still not hacking code), allow a harmonization flow to use different mappings:

1. Load Source Data 1 associated with Product entity.
2. Load Source Data 2 associated with Product entity.
3. Create Mapping 1 for "sku" -> "sku".
4. Create Mapping 2 for "SKU" -> "sku".
5. Create Harmonization Flow 1 with Mapping 1.
6. Run Harmonization Flow 1.
7. Update Harmonization Flow 1 to use Mapping 2.
8. Run Harmonization Flow 1.

The above only needs one harmonization flow instead of two.

Yet another way (still not hacking code), allow for N-to-one mappings:

1. Load Source Data 1 associated with Product entity.
2. Load Source Data 2 associated with Product entity.
3. Create Mapping 1 for "sku" OR "SKU" -> "sku".
4. Create Harmonization Flow 1 with Mapping 1.
5. Run Harmonization Flow 1.

The above only needs one harmonization flow and one mapping.

Probably makes sense to include all these features in the UI. Allow a user to:

- Point a harmonization flow at a source data subset.
- Switch a harmonization flow between different mappings. 
- Create N-to-1 mappings.

**Comment by aebadirad** [comment]
Data Hub 5.0 supports more methods to handle this, 4.x and before can use the recommended work arounds listed above.
