### ISSUE TITLE
Unit testing with ml-data-hub:2.0.4

### ISSUE THREAD

**Issue by markschiffner** [marklogic/marklogic-data-hub#1270]
I am trying to integrate ml-unit-test into ml-data-hub:2.0.4.

1. Test app server not getting created, I followed (marklogic/marklogic-data-hub#1090), but still not working. Tried adding mlTestRestServerName and mlTestDbName - is issue #26 related ticket?
2. Is there a preferred/convention location to put test modules? I am placing them under data-hub/test/...
3. I am guessing that all the appropriate data hub directories get added to mlModulePaths and that I need to add the test directory as normal. Are the data hub paths added so that I just have to assign the test directory in the properties file, or do I need to delineate all the data hub paths?

### Welcome Hub enthusiast!
Let's get the most out of this ticket.
#### The issue

Short description of the problem: Trying to integrate ml-unit-test

What behavior are you expecting? bullets above

#### Tech details

Which Operating System are you using? Mac OS

Which version of MarkLogic are you using? 9.0-4

Which version of the Data Hub Framework are you using? 2.0.4

Is this a QuickStart UI bug? If so, which browser are you using? No

#### The devil is in the details...

If possible, rerun the command with -d for debugging output and attach the output: N/A

  **for quickstart:**  
  `java -jar quickstart.war -d > myoutput.txt`

  **for gradle:**  
  `gradle mlYourCommand -d > myoutput.txt`

**Comment by markschiffner** [comment]
If it is not supported, is there alternative that folks are using.

**Comment by grechaw** [comment]
Hi @markschiffner since you brought this issue up some work has gone on in the community to get some information together about ml-gradle and data hub.  

 https://github.com/marklogic-community/ml-unit-test/wiki/Integrating-with-DHF

I'm not sure whether the approach will work with 2.x branch or not.. much of what we've tried to do since then is align DHF more closely with ml-gradle.

I'm going to close out this issue as part of a kind of extreme triage, but feel free to reopen if there's more to dig into.
