### ISSUE TITLE
Orchestrate harmonization of staged data since the last time the harmonization flow was run

### ISSUE THREAD

**Issue by jmakeig** [marklogic/marklogic-data-hub#1328]
As an ETL Developer, I want to be able to periodically load in batches of data from the same source and run harmonization on the new data, i.e. since I last ran it. I’d like to orchestrate the loading and harmonization externally, for example, from NiFi or a custom application. 

The [documentation for the REST harmonization endpoint](https://marklogic.github.io/marklogic-data-hub/harmonize/rest/) indicates that it bypasses the collector:

> You can skip the collector phase and go to the harmonize phase by invoking the REST Client API “flow” extension that gets installed when you set up DHF. To use the extension, send a POST HTTP request to /LATEST/resources/flow.

Where “can skip” seems to mean “*must* skip”. 

Ideally, I’d be able to kick off a harmonization flow from REST, Java, or Gradle and pass it parameters, such as `dataSourceID` and `lastHarmonizationDate`, and have the collector be able to use those to run the appropriate query.

**Comment by aajacobs** [comment]
+1

**Comment by josvr** [comment]
Justin, what is the status of this one? Can you increase prio?  Customers need this. This issue can be abstracted to the issue that we want better control over batch and RT-processing. So beside running harmonization since last run this includes only harmonize data for a particular MLCP / DMSDK run (Issue #1534 ). Also for realtime  you want to have a single point ingest-harmonization extension point (Issue #1535). I believe also Damon Feldman is working on better coordination of processing of batches/RT. Please get this shipped ASAP.

**Comment by josvr** [comment]
So +1
