### ISSUE TITLE
Consistent Database Naming Conventions

### ISSUE THREAD

**Issue by gregnist** [marklogic/marklogic-data-hub#1341]
#### The issue

Not a technical bug, but there is an inconsistency when creating a brand new data hub using QuickStart with regard to the default database naming conventions. Specifically, the modules database being created in staging does not align with the pattern present in all the other database names.

Based on all the other database naming convention defaults I would expect it to be:

`<hubName>-staging-MODULES`

However it is defaulting to:

`<hubName>-MODULES`

Please see the screenshot. 

#### Tech details

CentOS7
MarkLogic 9.0-2
DHF 4.0.0
Firefox

#### Screenshot

![image](https://user-images.githubusercontent.com/1749707/45501887-81568d80-b750-11e8-8ea8-52ad14b25872.png)

**Comment by grechaw** [comment]
Hi Greg, yes we decided to do this because a couple of weeks ago DHaaS finalized its architecture with a single database.  It was too late for us to go back, but we reverted the name of the staging modules db so as to prepare for the removal and re-merging of the final modules db.  I'll close this issue to keep it from synching around to various systems :)
