### ISSUE TITLE
RFC: Distribute DHF modules as a separate package

### ISSUE THREAD

**Issue by rjrudin** [marklogic/marklogic-data-hub#1463]
A benefit of the DHF Gradle plugin today is that by simply adding it to build.gradle, the DHF modules come along with it - i.e. they're automatically loaded for you. But there are some downsides to this:

1. We've seen bugs related to the fact that DHF needs multiple ways of loading modules - one for its own modules, and then another for what's under src/main/ml-modules
1. It's very difficult if, as a developer, I want to modify some of the DHF code for my project (and then ideally contribute it back later as a PR); this is easily done with smart-mastering (SM) or marklogic-unit-test (UT)

I mention SM and UT above because I think it would be better overall for DHF modules to be packaged up and distributed in the same fashion as SM and UT - i.e. a "com.marklogic:data-hub-modules:version" package would be published to jcenter, and it would then be pulled down via ml-gradle's "mlRestApi" package, just like SM and UT (see https://github.com/marklogic-community/ml-gradle/wiki/Depending-on-external-packages-of-modules for more info - and "mlModules" would have been a better name for this Gradle configuration, a future version of ml-gradle may add that as an alternative and deprecate "mlRestApi" which isn't as self-documenting). 

An immediate downside is that a developer now needs two bits of config in her build.gradle file instead of just one:

    plugins { id "com.marklogic.ml-data-hub" version "4.0.1" }
    dependencies { mlRestApi "com.marklogic:ml-data-hub-modules" version "4.0.1" }

Another downside/complication - how does this work with the quick start app? I'm not sure about that yet. 

But the benefits address the downsides of the current approach:

1. DHF modules "just work" now - they're no different than any other mlRestApi dependency in ml-gradle. No need for any additional code for loading modules, no more bugs specific to DHF re: loading modules (if there's a bug with loading modules, it has to be a bug in ml-gradle as well). 
1. DHF modules can be easily modified by a developer during development - i.e. as part of debugging (like adding logging), or to test out a change that would become a PR later. 

In addition, for a developer using SM and UT, her build.gradle file looks like what I think would be expected for an application with 3 dependencies on ML libraries:

    dependencies {
      mlRestApi "com.marklogic:ml-data-hub:4.0.1"
      mlRestApi "com.marklogic:smart-mastering-core:1.1.0"
      mlRestApi "com.marklogic:marklogic-unit-test:0.12.0"
    }

Overall, I think this would be a lot simpler and easier to understand, and of course involve a lot less code in DHF.

**Comment by aajacobs** [comment]
+1 for the simplification and standardization.  I've been using this approach with Smart Mastering and it's really easy to override the Jcenter package to make your own versions for testing/PRs, and revert back to the new jcenter package when desired.  Plus everything is standard ml-gradle, so no need to learn new SM-specific tasks (except loading match and merge options).

**Comment by damonfeldman** [comment]
+1 - I find a huge number of discussions and inefficiency stem from DHF and ml-gradle differences. Not only do people not know how things work or have easy access to the code - they don't even know what group or resource to go to because some errors are from ml-gradle use, and some are from specific DHF-gradle use.

**Comment by grechaw** [comment]
@aebadirad has certainly been in discussions with @rjrudin about how to move forward with this mess.  Please make sure @sbayatpur-ml has prioritization inputs.

**Comment by jmakeig** [comment]
@damonfeldman, thanks for the feedback. However, before we jump into a solution, I want to make sure we’re clear about the problem and its impact urgency. 

I think these are the use cases we expect to work: 

1.  As a Hub Developer, I need to be able to update my code locally and have a reliable and efficient way to push the updated code to my DHF instance, on-prem or in a cloud DHS instance.
1. As a Hub Developer, I also need to deploy other MarkLogic configuration along with my DHF-specific configuration, such as REST Extensions, index settings, or back-up configuration. (In DHS this surface area is greatly reduced, but non-zero.)
1. As a Hub Admin, I need to be able to update my on-prem DHF product independently of the user code/configuration. (We, MarkLogic Engineering, also need a way to update just the hub code and not have the user’s next deployment overwrite that.)
1. As a Smart Mastering or Hub Contributor, I need to be able to easily fork the product code with my own version to develop and test my local changes.

What have I missed/misconstrued? 

Given the set of expected behavior, what’s broken/insufficient today? Are there workarounds? What’s the impact? 

Once we’re clear on those problems and priorities we’ll have a better idea of possible solutions.

**Comment by josvr** [comment]
+1

**Comment by rjrudin** [comment]
Closing this, will track in JIRA as the priority of this arises.
