### ISSUE TITLE
Autogenerated code should handle null values correctly

### ISSUE THREAD

**Issue by netdance** [marklogic/marklogic-data-hub#1548]
Autogenerated code for content.sjs handles missing elements correctly, but not null values.

Generated code looks like this:

  let sku = !fn.empty(fn.head(source.xpath('//SKU'))) ? xs.string(fn.head(fn.head(source.xpath('//SKU')))) : null;

It should instead look like this:

  let sku = fn.empty(fn.head(source.xpath('//SKU'))) || fn.head(source.xpath('//SKU')).toObject() === null ? null :  xs.string(fn.head(fn.head(source.xpath('//SKU'))));

**Comment by srinathgit** [comment]
Thank you for the input. We will consider including this change in the auto generated code

**Comment by aebadirad** [comment]
With the move to Data Hub 5.0, we'd encourage any enhancements to 4.x's code generation line be a PR to the 4.x-develop line and we can package it for a patch release if you still wish this accomplished.

Otherwise, will close this issue. Please reopen with the PR if you'd like this included, it'd be much appreciated.
