### ISSUE TITLE
hubGenerateTDETemplates only generates TDE's for staging database (v4.0.3)

### ISSUE THREAD

**Issue by derms** [marklogic/marklogic-data-hub#1618]
#### The issue

hubGenerateTDETemplates only generates TDE's for staging database

Should generate for the final DB also

#### Tech details

v4.0.3 of DHF

#### The devil is in the details...

GenerateHubTDETemplateCommand#execute() method only generates code in hubConfig.getStagingAppConfig().getSchemasPath()

It should also generate the code in hubConfig.getFinalAppConfig().getSchemasPath()

There should be an option "target" so that you can choose to generate the code for staging or final only (it should generate both by default)

**Comment by derms** [comment]
workaround (for 4.0.3) is available at 

https://gist.github.com/derms/d80bac901682c22006aa0b4c37624146

**Comment by akshaysonvane** [comment]
Hi @derms, Thanks for filing the issue.
As its more likely that users will want TDE templates for the Final DB instead of staging DB, the command now generates the TDE templates for Final DB. This change has been added to the develop branch.
Also as its just generating code, you can copy the generated modules to the right path under staging.

**Comment by aebadirad** [comment]
Fixed in version 4.2.0
