### ISSUE TITLE
Provide runCollector in flowlib.sjs like in flow-lib.xqy

### ISSUE THREAD

**Issue by josvanroosmalen** [marklogic/marklogic-data-hub#1674]
Currently there is no `runCollector` in `flowlib.sjs`. There is one in `flow-lib.xqy`.

For SJS it is now impossible to run the collector directly (e.g. a realtime rest endpoint which want to harmonize straight away) eg because more entities can be impacted than only the ingested data (eg in case of update).

**Workaround:**

**Use XQuery:**

```
const flq = require("/data-hub/4/impl/flow-lib.xqy");
const fl = flq.getFlow(entity, entityName, consts.HARMONIZE_FLOW);
return flq.runCollector(fl,jobId,options);
```

**Use SJS:**

```
const harmonizeFlow = flowlib.getFlow(entity, flowName,consts.HARMONIZE_FLOW);
const collector = require(harmonizeFlow.collector.module)["collect"];
return collector(options);
```

**Comment by akshaysonvane** [comment]
Thanks for creating the issue.
Tracking it via Jira: https://project.marklogic.com/jira/browse/DHFPROD-1650

**Comment by aebadirad** [comment]
This workaround is acceptable for now. We won't be updating the datahub 4.x's way of running code, but we have made this possible for data hub 5.0 on the data hub core object which you can require into your app and organize/orchestrate as you need.

You can even just feed the datahub a direct set of URI's you'd like to operate against and do your own searching/collection mechanism if you want to get ambitious.

I'm going to close this because we won't be doing the work here in 4.x for that, however, we are open to enhancing more advanced usages in 5.0.
