### ISSUE TITLE
Make DHF documentation searchable

### ISSUE THREAD

**Issue by nizdobs** [marklogic/marklogic-data-hub#1720]
There's a tremendous amount of useful information in:

https://marklogic.github.io/marklogic-data-hub/
and
https://marklogic.github.io/marklogic-data-hub/docs/

but it can be hard to find specific information/commands. I don't see any way to search this documentation on marklogic.github.io.. If github.io doesn't provide search capabilities then I think it makes more sense to host the DHF documentation within docs.marklogic.com

**Comment by akshaysonvane** [comment]
Yes, this will be quite helpful.
Tracking it via https://project.marklogic.com/jira/browse/DHFPROD-1669

**Comment by eltesoro-ml** [comment]
Tracking in an even older JIRA issue: https://project.marklogic.com/jira/browse/DHFPROD-846, which was generated from https://github.com/marklogic/marklogic-data-hub/issues/978.

**Comment by eltesoro-ml** [comment]
> If github.io doesn't provide search capabilities then I think it makes more sense to host the DHF documentation within docs.marklogic.com

Docs.marklogic.com uses different tools (Framemaker with binary content files) and different build processes and the docs are published only when the product is released.

My understanding is that DHF docs were separated from the main docs to be able to be more Agile with the doc process (we can publish anytime), and to be more transparent (using Markdown and HTML and storing content as text files).

As a side-effect, DHF does **not** become dependent on old versions of proprietary third-party tools that are no longer supported but can't be upgraded because our old fragile build process would break.

So it doesn't make sense to convert content using more recent technologies to formats using old technologies just to get search functionality.

**Comment by rjrudin** [comment]
Closing this, as docs for DHF 5 are searchable - https://docs.marklogic.com/datahub/ - but I doubt we'll ever go back to rework the DHF 4 docs to make them searchable.
