### ISSUE TITLE
Allow multiple Content returns, looping plugin calls for a single collector URI

### ISSUE THREAD

**Issue by mikrovvelle** [marklogic/marklogic-data-hub#1892]
#### The issue

In pre-4 DHF versions, you could generate multiple entity instances from a single Content module invocation. This was crucial for harmonizing data from large, complex JSON and XML source documents, such as a pharma trial status report with multiple patients, events, drugs, etc.

The flow went like this:

- `collector` output / content input: URI of source doc
- `content` output (runs once per URI): a set of entity instances (*N* many), each one representing a portion of the original document.
- `triples` (runs *N* times per URI): some semantic info based on the individual instance.
- `headers` (runs *N* times per URI): some header info based on the individual instance
- `writer` (runs *N* times per URI): writes to Final database.

All it took to implement this pattern was a simple change to the `main` module of a harmonization flow. 

From this (generated DHF `main.xqy`):

```xqy
declare function plugin:main(
  $id as xs:string,
  $options as map:map)
{
  let $content-context := dhf:content-context()
  let $content := dhf:run($content-context, function() {
    content:create-content($id, $options)
  })

  let $header-context := dhf:headers-context($content)
  let $headers := dhf:run($header-context, function() {
    headers:create-headers($id, $content, $options)
  })

  let $triple-context := dhf:triples-context($content, $headers)
  let $triples := dhf:run($triple-context, function() {
    triples:create-triples($id, $content, $headers, $options)
  })

  let $envelope := dhf:make-envelope($content, $headers, $triples, map:get($options, "dataFormat"))
  return
    dhf:run-writer(xdmp:function(xs:QName("writer:write")), $id, $envelope, $options)
```

To this (note the `let $contents` and `for $content in $contents`):

```xqy
declare function plugin:main(
  $id as xs:string,
  $options as map:map)
{
  let $content-context := dhf:content-context()
  let $contents := dhf:run($content-context, function() {
    content:create-content($id, $options)
  })

  for $content in $contents

  let $header-context := dhf:headers-context($content)
  let $headers := dhf:run($header-context, function() {
    headers:create-headers($id, $content, $options)
  })

  let $triple-context := dhf:triples-context($content, $headers)
  let $triples := dhf:run($triple-context, function() {
    triples:create-triples($id, $content, $headers, $options)
  })

  let $envelope := dhf:make-envelope($content, $headers, $triples, map:get($options, "dataFormat"))
  return
    dhf:run-writer(xdmp:function(xs:QName("writer:write")), $id, $envelope, $options)
};
```

As of version 4, this method is broken. The writer will somehow only run once per URI. So now using this method, instead of writing all of the instances to the Final database, only one instance gets written per URI (not *N*).

There no longer seems to be a straightforward way to break a large, complex source document down into the multiple Final entities that it represents. This seems like a regression, and will require a lot of (potentially complicated and error-prone) harmonization-flow re-writes from clients who have used this pattern.

#### Tech details

- DHF 4.1.0, 4.1.1
- Could be related to #391

**Comment by rjrudin** [comment]
I think this is an area where DHF is more complicated than the traditional ML tool for batch processes that collect a bunch of IDs/URIs and do something with each of them - corb. Corb has two concepts - a collector, and a transformer, where the transformer can do anything, and thus supporting a 1:many relationship between identifier and output document is trivial.

I think I understand the rationale behind having separate content/headers/triples/writer modules, but instead of forcing that structure, I think it'd be more flexible to generate a single "transform" module (or "harmonize"?) that has stubbed-out functions for constructing content, headers, and triples, and then writing them out. That would give a user the ability to do whatever they want, just like in corb, but they'd at least have the initial encouragement of thinking in terms of content/headers/triples. In effect, this would be reuse via composition (optionally invoking functions) instead of via inheritance (being forced to implement certain modules and living with the workflow imposed by the thing calling those modules).

**Comment by clockworked247** [comment]
Adding PM to the conversation to comment.  @jmakeig @popzip

**Comment by sashamitrovich** [comment]
On projects, we often (in fact most often) have the situation that the Content is creating multiple docs out of one initial URI. We have projects that depend on this! Think of the migration path of this code when you think of bringing in breaking changes such as this, please.

**Comment by aebadirad** [comment]
Data Hub 5.0 now allows for this. Please upgrade to 5.0.
