### ISSUE TITLE
Quickstart: Deleting steps "Mapping" and "Custom" doesn't clean up filesystem artifacts

### ISSUE THREAD

**Issue by masyukun** [marklogic/marklogic-data-hub#2571]
#### The issue

Deleting a mapping step and deleting a custom step do not clean up after themselves in the filesystem. Even after they're gone from QuickStart, their artifacts exist in 

- ./mappings/`<name>`/`<name>`-0.mapping.json
- ./src/main/ml-modules/root/custom-modules/custom/`<name>`/main.sjs and 
- ./step-definitions/custom/`<name>`/`<name>`.step.json 

In contrast, deleting a flow correctly removes the ./flows/ artifact.

#### Tech details

Which Operating System are you using? Windows 10

Which version of MarkLogic are you using? MarkLogic 9.0-9.1-amd64

Which version of the Data Hub Framework are you using? DHF 5.0.0

Is this a QuickStart UI bug? If so, which browser are you using? Yes; Google Chrome 74.0.3729.169 (Official Build) (64-bit)

**Comment by ayuwono** [comment]
Tracking this on JIRA: https://project.marklogic.com/jira/browse/DHFPROD-2599

**Comment by aebadirad** [comment]
Mappings can apply across flows, so that makes sense, we plan to make this a bit easier to see and reuse soon as we introduce declarative mapping.

As for the step-definitions (which are tied to modules), currently quickstart does mix the creation of a custom step and step definition (as both are done for you by quickstart). This would probably be made more clear if the UI allowed you to make custom step definitions in one section of the UI and then select them in the custom step of a flow builder. That way deleting a step and a step-definition are two discrete things.


Would this presentaion make more sense @masyukun ?

**Comment by kkanthet** [comment]
fixed as part of 5.0.2 release
