### ISSUE TITLE
Provenance missing database context when referencing a URI location

### ISSUE THREAD

**Issue by markplotnick** [marklogic/marklogic-data-hub#2588]
In current examples (and confirmed by Alex Ebadirad in response to Tech Summit questions),
when provenance information references a document URI there is no accounting for which database the URI resides in. In a multi-database system (staging-db, final-db, job-db, etc.), having the URI without the context of the database for the **location** is insufficient and will be problematic for actual use-cases when provenance data is being put to the test.

I propose that provenance location include the uri's database by default, with the possible option of excluding it via a configuration option (for example, in a single content-db implementation).

I am neutral to how the uri's database reference should be implemented.

One suggestion is to use a similar notation to remote dir/file access in unix systems:
[database]:[uri] 

For example:
"staging-db:/content/ingest/equipment/oil-platform/pressure-monitor.json"

**Comment by rjrudin** [comment]
Is this primarily for a reference from a final document back to the 1+ documents in staging that mapped to it? 

If so, I'm wondering how useful having the name of the staging database would be, as wouldn't it be understood that the staging database was the source the vast majority of the time?

I'm thinking instead of the source database being a JSON object that always has a URI, and then optionally a database name too, which would not be included by default because I think most of the time, it would not be helpful (but a user could configure that it be included):

```
"source-database": {
  "uri": "some uri"
}
```

**Comment by markplotnick** [comment]
Big picture, I see the hubs could evolve to multi-multi-db solutions. Especially with multi-mastered solutions and db replication involved. If the provenance is useful, I think we should lean towards being more explicit by default. But I am all for making it is a compact as possible.

**Comment by rjrudin** [comment]
We're tracking this as part of enhancing provenance in either 5.5 or 5.6
