### ISSUE TITLE
Custom step documentation is incomplete

### ISSUE THREAD

**Issue by damonfeldman** [marklogic/marklogic-data-hub#2773]
#### The issue

Some types of custom steps are not covered in the custom step documentation.

#### What behavior are you expecting?
The custom step example here: https://docs.marklogic.com/datahub/ should cover more cases. In particular:
* The example code does not use the makeEnvelope() function, but probably should.
* The example is only for harmonize flows

The signature of makeENvelope is incomplete, in that the content object must conform to a very specific structure
* For json, it should include instance data and specific propperties "$type" and "$version" with (optional?) $attachment also. 
e.g. 
{ 
    "person" : myPersonData,
    "$type" : "Person"   // the entity name
   "$version": "0.0.1"
   "$attachment" : "bob,jones,123 main st,newton,ma,02441"
}
* however, for XML the makeEnvelope appears to require the data (myPersonData) to be put in a "$ref" property.

Which version of the Data Hub Framework are you using?
5.0.1

## ideal doc recommendation
Each of the following should be fully documented
* what to return from main.sjs from an input flow
   * both when harmonizing and writing a single item, and when writing an array of items
* what to return from main.sjs for a harmonize flow
   * both for one item and many items
* specify that makeEnvelope() should be used (or not used) and what format it produces
* specify the required inputs to makeEnvelope, and particularly specify all required properties on the inputs (e.g. $type, $attachment, $ref and $version)

#### code changes to make signatures more clear
Better yet, update makeEnvelope() to take in the required parameters, rather than embedding them in the content object, to make the signature more clear.

And define objects with helper methods such as "writeSpec" with a setUri(), setContent(), setHeaders(), setCollections() and other methods so people can interact with the objects that are expected by DHF 5, rather than be coupled to the specific JSON formats.

Ideally, the objects would also have verify() functions that report in a clear way if there is missing or invalid data.

**Comment by sbayatpur** [comment]
Associated Jira story: https://project.marklogic.com/jira/browse/DHFPROD-2879

**Comment by rjrudin** [comment]
@damonfeldman In your custom step, which conversions were you attempting?

1. JSON -> JSON
1. XML -> XML
1. XML -> JSON
1. (guessing "no" for this one) JSON -> XML

**Comment by damonfeldman** [comment]
I am not sure what we were working on for this ticket anymore, but I think it was XML -> XML. Our current code returns:
  return {
    '$ref' : instance,
    '$attachments': attachments,
    '$type': 'publication',
    '$version': '0.0.1'
  }

for one (publication) entity. That's the only XML target entity we have.

**Comment by damonfeldman** [comment]
The docs I was looking at when I entered the ticket had a main.sjs flow, rather than the current link above. It may have changed since then. 

The current docs should be more in terms of functions and signatures. The full "path" from zero to a working custom step as I understand it is to:

* create a flow with a "CUSTOM" step. The format and location of the *.flows.json files should be specified. e.g. both the JSON structure and the "flows" directory location in the build structure.
* create a step file (*.step.json) again with the path (step-definitions/custom/<flow name from flow file>/<flow name>.step.json)
* create an .sjs module with a function main (contentDesc, options)
   * the required attributes of contentDesc, such as contentDesc.uri, etc., and how/if it can be an array.
  * the return type. In particular, if it is a JSON or XML document (or a map) what properties it must have.

As noted, ideally someday defined input/output objects with setters that are validated by the framework as being complete, would be ideal, so they can have meaningful errors and make it clear from inspection what is needed for the flow to work.

**Comment by rjrudin** [comment]
I just tested creating a custom step via QS and via Gradle. In both cases, the following are stubbed out - we'll call the name of it "my-step":

- ./step-definitions/custom/my-step/my-step.gradle.json
- ./src/main/ml-modules/root/custom-modules/custom/my-step/main.sjs

So it's a one-click process to get everything setup so that you can start modifying main.sjs. That module has better comments in it than what's documented at https://docs.marklogic.com/datahub/modules/creating-custom-step-module.html , which definitely needs updating. 

I think the following changes are then worthwhile:

1. Modify https://docs.marklogic.com/datahub/modules/creating-custom-step-module.html so that it describes what's passed into the module, what needs to be returned, and refer to an example project that shows a custom step module (which I think is more helpful than showing something out of context). 
1. Modify https://docs.marklogic.com/datahub/flows/configure-custom-step-using-quickstart.html to link the above page
1. Modify https://docs.marklogic.com/datahub/flows/create-step-using-gradle.html to link to the above page so that if a user creates a custom step, they know where to go to learn how to modify that custom step module 

In terms of modifying the generated main.sjs to make it more helpful, I believe @aebadirad has a separate effort in place to add helper functions and more comments. Specifically, that's this ticket - https://github.com/marklogic/marklogic-data-hub/issues/2714

**Comment by lrzedzicki** [comment]
Hi,

We've had another support issue from one of our customers, complaining about lack of documentation for a custom step in DHF5.
I've encouraged them to file a separate issue for any particular bugs they've encountered.
In the meantime please see here for more details:
https://help.marklogic.com/staff/Tickets/Ticket/View/22565

And a +1 for more DHF5 custom step documentation

**Comment by kkanthet** [comment]
Issue Fixed in 5.4.0 release
