### ISSUE TITLE
Running mlLoadModules causes Java 9+ error

### ISSUE THREAD

**Issue by sashamitrovich** [marklogic/marklogic-data-hub#2893]
### Welcome Hub enthusiast!

Let's get the most out of this ticket.

#### The issue

Short description of the problem:
Running 
What behavior are you expecting?

#### Tech details

Which Operating System are you using?
MacOS 10.14.6 Mojave

Which version of MarkLogic are you using?
DHS (latest release on AWS)

Which version of the Data Hub Framework are you using?
4.3.1

Is this a QuickStart UI bug? If so, which browser are you using?
No

#### The devil is in the details...

If possible, rerun the command with -d for debugging output and attach the output:

  **for quickstart:**  
  `java -jar quickstart.war -d > myoutput.txt`

  **for gradle:**  
  `gradle mlYourCommand -d > myoutput.txt`

[myoutput.txt](https://github.com/marklogic/marklogic-data-hub/files/3498013/myoutput.txt)

**Comment by rjrudin** [comment]
I think you need to clarify that this is when you deploy to DHS with SSL enabled. I recommend including your gradle-*.properties file (without any passwords or hostnames in it).

**Comment by sashamitrovich** [comment]
This is happening when deploying to DHS using SSL enabled in in the gradle.properties.

**Comment by rjrudin** [comment]
@sashamitrovich  @ehennum @aebadirad  @sbayatpur   The issue is that DHF 4.3.1 is using ml-app-deployer 3.12.0, which was not yet setting a default/simple impl of TrustManager on the DatabaseClient. That was fixed in 3.15.0 - https://github.com/marklogic-community/ml-app-deployer/issues/361 . The Java Client is fine - but without a TrustManager, it's then hitting the code path in OkHttp that blows up when running on Java 9 or greater. 

DHF 5.0.1 (not 5.0.0) is using ml-app-deployer 3.15.0, and thus it and all greater versions will work properly on Java 9 or greater.

The good news - 4.3.2 is using ml-app-deployer 3.16.0, and thus this problem does not occur in 4.3.2.

So the resolution to this should be for clients on 4.3.1 to just bump up to 4.3.2.

**Comment by sashamitrovich** [comment]
Confirming the issue is solved with 4.3.2.
Thanks!
