### ISSUE TITLE
mlAppReached limit of 30

### ISSUE THREAD

**Issue by AgricaSopraSteria** [marklogic/marklogic-data-hub#2948]
**The issue**

Sometimes get an error : mlAppReached limit of 30 and MarkLogic has not restarted yet; check MarkLogic status

**Tech details**
Which Operating System are you using? Red Hat Entreprise Linux

Which version of MarkLogic are you using? 9.0-9

Which version of the Data Hub Framework are you using? 2.0.0

![image](https://user-images.githubusercontent.com/41364914/64847401-38f5d800-d60f-11e9-9d4d-9c831fd4f96b.png)

**Comment by rjrudin** [comment]
That message will be printed when mlDeploy is waiting for MarkLogic to restart. It appears that it's a call to manage/v2/mimetypes that's causing ML to restart, which is expected. DHF will wait up to 30s for ML to restart before moving on. But then the I/O error occurs because ML is likely still restarting. 

Some thoughts:

# I believe DHF 4 has some smarts in it for not deploying mimetypes unless they're new and/or have changed. This avoids unnecessary restarts. 
# You're on DHF 2.0.0, which isn't supported, so that's another reason to try upgrading to DHF 4. 
# But I'd look further into why it's taking ML so long to restart. Try restarting it manually - does it typically take over 30 seconds?

**Comment by rjrudin** [comment]
Closing due to lack of response
