### ISSUE TITLE
RFE: detailed documentation of DHF json files

### ISSUE THREAD

**Issue by JackYoungblood** [marklogic/marklogic-data-hub#2966]
### Welcome Hub enthusiast!

Let's get the most out of this ticket.

#### The issue
It would be very helpful to have detailed documentation of every json property for scaffolded DHF json files (i.e. entity.json, flow.json, step.json, etc.). I've been trying to do more of my DHF work from gradle but it's impossible without documentation about how to configure these scaffolded DHF json files to do what I need them to do (I'm currently using DHF 5.0.2.

**Comment by brucean52** [comment]
JIRA ticket: https://project.marklogic.com/jira/browse/DHFPROD-3179

**Comment by rjrudin** [comment]
Flows are documented at https://docs.marklogic.com/datahub/5.2/flows/flow-definition.html - that may not have existed in the DHF 5.0.2 timeframe.

The syntax of an entity model is defined in the ML docs at https://docs.marklogic.com/guide/entity-services/intro 

Closing this under the assumption that this addresses the issue. Because this issue is a bit old, please create a new one for questions that you have about config where the docs don't seem to provide the answer.
