### ISSUE TITLE
DHF 5.0.3 (target URI replace)

### ISSUE THREAD

**Issue by sundarbandepalli** [marklogic/marklogic-data-hub#3027]
#### The issue

Even when you include Target URI replace, generate URI is still set to true while ingesting text files delimited with either tab or I

What behavior are you expecting?

When you include a customized URI, generate URI should be set to false in the mlcp command and system should not try to generate a URI with my local machine name path etc. 

Which Operating System are you using? Mac OS

Which version of MarkLogic are you using? 9.0-10.3

Which version of the Data Hub Framework are you using? 5.0.3

Is this a QuickStart UI bug? If so, which browser are you using? Chrome.

**Comment by srinathgit** [comment]
Are you referring to the mlcp command that you see in the bottom of the ingest screen ? If so, since  DHF generates a new uri that appends UUID every time you run the step, it is included in mlcp command.

**Comment by rodgersandrew** [comment]
I believe this is the same issue:

When ingesting through custom ingestion module, setting content.uri has no effect on the resulting uri. It appears that the ingestion step is still effectively generating a UUID for the URI regardless of what is set during the custom step.

**Comment by kkanthet** [comment]
@sundarbandepalli I guess the  question is , It is expected  that UUID will be generated. What is the issue ?

**Comment by bsrikan** [comment]
@rodgersandrew ingestion step, custom or regular, will generate UUID when processing delimited input files. `content.uri` might look something like `/admissionComplete/datasets/admissions-core/02860af9-4e4f-44e0-a1b0-1023d96cc489.json`.
For delimited files a document is generated for every row and so every document must get a unique URI, which is guaranteed by appending UUID.

content.uri in custom step gives you an option to edit the URI(which includes the UUID in case of delimited files)

You can use substring to replace UUID with your own unique identifiers. Otherwise you will run into `"XDMP-CONFLICTINGUPDATES` if all the documents get the same URI.

**Comment by rjrudin** [comment]
Closing based on above response
