### ISSUE TITLE
Ability to set document quality to be used

### ISSUE THREAD

**Issue by kghmanuel** [marklogic/marklogic-data-hub#3055]
#### The issue
Collection to be set can be supplied via context.collections. Document quality however does not take effect even if the following is set:
```
  context.metadata.quality = 15
  context.quality = 15
```
The metadata entry gets set and can be verified via qconsole. But the actual result of `xdmp:document-get-quality` remains 0.

I think this is expected since both `documentInsert` calls do not supply `quality` as an input. Rather, it is kept as part of metadata. See: https://github.com/marklogic/marklogic-data-hub/blob/master/marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/impl/hub-utils.sjs#L53

```
        temporal.documentInsert(temporalCollection, content.uri, content.value, 
          {
            permissions, 
            collections: collections.filter((col) => !temporalCollections[col]), 
            metadata
          }
         );
      } else {
        xdmp.documentInsert(content.uri, content.value, {permissions, collections, metadata});
```

#### Tech details

Which Operating System are you using? Windows 7

Which version of MarkLogic are you using? 9.0-9.1

Which version of the Data Hub Framework are you using? 5.0.2

Is this a QuickStart UI bug? If so, which browser are you using? Not QuickStart UI

**Comment by rjrudin** [comment]
@kghmanuel  What release are you looking for a fix in? As a temporary workaround, and if you're not planning on deploying to DHS (as overriding DHF modules is not allowed there), you could add a copy of hub-utils.sjs to your codebase and add support to writeDocuments so that quality is not ignored. Note that if you try to address this on the develop branch, the relevant code is in the new invoke-queue-write.sjs module.

**Comment by kghmanuel** [comment]
Preferrably a 5.X branch. When you say "add a copy of hub-util.sjs", do you mean the codebase of DHF or the app that uses DHF?

**Comment by rjrudin** [comment]
The workaround - outside of this PR - would be to add a copy of hub-utils.sjs to the codebase of the app that uses DHF. That would give you an immediate solution.

The next release will be 5.3.0, and that will likely be out in the summer. If you'd like to submit a PR for that, it looks like it's just a matter of updating invoke-queue-write.sjs on the develop branch to honor "quality" if it's part of the content.context object. We'd need tests for it though, and I'd probably want to rework invoke-queue-write.sjs so that there's a function that builds the object that's passed to temporal.documentInsert/xdmp.documentInsert so we can unit-test that function. 

This would be a small enough change that I think it'd be better to just push for having it included in 5.3.0 as opposed to having to setup a PR yourself for it.

**Comment by kghmanuel** [comment]
ok.. ill wait for 5.3 then.

**Comment by rjrudin** [comment]
This isn't planned for 5.3 though; you'd need to make a case to @sbayatpur to have it included. 

Note that you could also use a pre-commit trigger as a workaround in the meantime.

**Comment by sbayatpur** [comment]
@kghmanuel can you explain more about the use case for why how this is used? Is it right to assume that you are wanting to set be able to set context.quality in a custom module that would be referenced from a custom step in 5.x?

**Comment by rjrudin** [comment]
Being tracked via DHFPROD-6843
