### ISSUE TITLE
In QuickStart, if there are no documents relevant to a Mapping step, the mapping cannot be seen.

### ISSUE THREAD

**Issue by stuartMoorhouse** [marklogic/marklogic-data-hub#3082]
On the edit flow page, e.g., http://localhost:9080/#/edit-flow/otc-call-or-put-spread-to-services-model

The maps steps can be seen once they are configured. If you return to the page when there are no documents in scope for that mapping the database, they cannot be seen. This makes it appear to the user that the mapping information is gone and must be re-entered.

Having, once there are documents in scope for the mapping again, the mappings can be seen.

**Comment by srinathgit** [comment]
We use an ingested document in the staging db for the mapping. If you clear the staging database or don't have any docs that match the query used in mapping step, you will not be able to see it in the mapping page. However if you re ingest docs and  query used in mapping step returns any docs, we will choose one of them for the mapping step automatically. This behavior is by design.

Do you want a better message to be displayed in case there are no source documents ?

**Comment by rjrudin** [comment]
Closing due to no response
