### ISSUE TITLE
Error Extension hubstats does not exist.

### ISSUE THREAD

**Issue by maachou** [marklogic/marklogic-data-hub#328]
#### Short description of the problem:
After loading and harmonizing the "getting started tutorial" data, I'm unable to display the document counts per database in the dashboard page. 
In the error log it seems that the extension hubstat does not exist. The datahub framework is running on my mac and the datahub was installed on MarkLogic 8.0-6 in a Centos 7 VM.
Attached a screenshot of the dashboard page and the console error.
<img width="1440" alt="screen shot 2016-11-08 at 15 02 06" src="https://cloud.githubusercontent.com/assets/879083/20102654/24fc92ce-a5c7-11e6-8a19-b85b6088439b.png">
<img width="1425" alt="screen shot 2016-11-08 at 15 01 42" src="https://cloud.githubusercontent.com/assets/879083/20102653/24fa44ce-a5c7-11e6-9caf-d7cb320ca827.png">

**Comment by paxtonhare** [comment]
This can happen one of two ways:

1. You are on 1.0.0 and you pressed the broken Redeploy button. (This was fixed in 1.0.1)
2. You upgraded from a release candidate and didn't reinstall

Either way you can fix this with these instructions:
# The Fix

**First question:** Can you reinstall the hub? Or is there too much data such that you don’t want to reinstall?
 
**Second question:** Have you customized the gradle config json files under marklogic-config?
 
### Simple fix:
 
Assuming you can reinstall and you haven’t messed with marklogic-config then it’s pretty simple to fix. Let’s reset the game…
 
**From the UI**
1.       Delete the .tmp directory
2.       Go to the QuickStart UI and settings. Then uninstall
3.       Stop the running war file
4.       Delete the marklogic-config directory
5.       Make sure you are using the latest version (not an RC) of the war file
6.       Start the war again: java –jar quickstart.war
7.       Walk through the wizard and install
 
**From Gradle**
1.       Delete the .tmp directory
2.       Run gradle mlUndeploy
3.       Delete the marklogic-config directory
4.       Run gradle hubInit
5.       Run gradle mlDeploy
6.       Make sure you are using the latest version (not an RC) of the war file
7.       Restart the war: java –jar quickstart.war
 
 
**Not so simple Fix:**
If you can’t reinstall then you can manually get things working right.
 
1.       Delete the .tmp directory
2.       Stop the running war process
3.       Run gradle hubInstallModules
4.       Run gradle mlLoadModules
5.       Make sure you are using the latest version version (not an RC) of the war file
6.       Restart the war: java –jar quickstart.war
