### ISSUE TITLE
DH TDE can't retrieve value if newContent.value is changed?

### ISSUE THREAD

**Issue by chenfiona** [marklogic/marklogic-data-hub#3647]
*### Welcome Hub enthusiast!
Let's get the most out of this ticket, please fill out this template.
#### The issue
Short description of the problem:

What behavior are you expecting?
I have a custom step following mapping step. I can retrieve the values from the mapped properties in TDE without issue.
During the custom step, I would like to re-configure below:
#### Original custom module:
newContent.value  = envelope;

#### Re-configured:
newContent.value  = envelope;
newContent.value = { 'DataContent' : envelope.envelope.instance,
                       'DataProvenance' : envelope.envelope.headers,
                       'DataSource' : doc.toObject().envelope.attachments.envelope.instance
                  };
Then TDE can't retrieve value from the harmonised properties from the custom step. If I remove those lines and keep "newContent.value  = envelope;" as it is, then TDE works.

What are the steps to reproduce the issue:
Put below lines in the main module:
newContent.value  = envelope;
newContent.value = { 'DataContent' : envelope.envelope.instance,
                       'DataProvenance' : envelope.envelope.headers,
                       'DataSource' : doc.toObject().envelope.attachments.envelope.instance
                  };

#### Tech details

Which Operating System are you using?
Windows 7
Which version of MarkLogic are you using?
10.0-3
Which version of the Data Hub are you using?
5.1.0
Is this a QuickStart UI bug? If so, which browser are you using?
No.
#### The devil is in the details...

If possible, rerun the command with -d for debugging output and attach the output:

  **for quickstart:**  
  `java -jar marklogic-datahub-<version>.war  --debug  > myoutput.txt`

  **for gradle:**  
  `gradle mlYourCommand -debug > myoutput.txt`

**Comment by ryanjdew** [comment]
@chenfiona Thank you for filing an issue with us. The default TDE indexing relies on the documents stored in the database conforming to the envelope model. You can read more about the envelope pattern on our documentation site [here.](https://docs.marklogic.com/datahub/about/envelope-pattern.html) 

In order to give our users a better experience, we'd love to hear more about the reasoning behind the different data model structure you're using and ways we can simplify the problem you're trying to solve.

That being said, there is a way you can adjust the TDEs to conform to your model by following the steps below.

1. Run `./gradlew hubDeployUserArtifacts`.
2. Run `./gradlew hubGenerateTDETemplates`. This will place the TDE templates into your project under `<data-hub-project>/src/main/ml-config/databases/data-hub-final-SCHEMAS/schemas/tde/*.tdex`
3. Edit the top-level `tde:context` value in your .tdex file with the appropriate XPath to your Entity Instance. e.g., `<tde:context>/*:DataContent</tde:context>`.
4. Run `./gradlew mlLoadSchemas`
5. Wait for indexing to complete. (This can be monitored in the MarkLogic Admin UI, which by default runs on port 8001)

Note that if you take these steps that the TDEs will become managed by you. This means any updates to your Entity Models will **not** be reflected in your TDE indexes unless you manually update them. You can read more about using TDEs [here.](http://docs.marklogic.com/guide/app-dev/TDE)

**Comment by ryanjdew** [comment]
@chenfiona You can set your Entity Name to "DataContent" and your context will be set to instance/[DataContent].

Also, I think I may have been unclear/ambiguous in my statement about the manual process for the TDE. The manual process will only be applicable when the Entity Model (or document structure) changes. So the volume of data is less relevant than how often you are changing the structure/schema of that data.

**Comment by rjrudin** [comment]
https://docs.marklogic.com/datahub/5.4/entities/about-entities.html describes how you can insert your own TDE such that DHF will not generate its own. That's often desirable when the DHF-generated one isn't quite what you want, and you don't want the overhead of multiple TDE templates. 

Based on this and the above response, I believe the questions have been addressed here. For additional questions pertaining to the DHF-generated TDE, please open a new ticket.
