### ISSUE TITLE
DHF5 fails with silence if uri is not there

### ISSUE THREAD

**Issue by josvanroosmalen** [marklogic/marklogic-data-hub#3839]
A step fails (at least in 5.1) automatically and with silence (! only log) if the `uri` is not present. For example if a custom step is removing/overwriting the URI with null, etc. 

This should fail hard because the intention is to write a document. 

```
  addToWriteQueue(content) {
    if (content.uri) {
      this.writeQueue.push(content);
    } else {
      this.datahub.debug.log({ type: 'error', message: `Couldn't add '${xdmp.toJsonString(content)}' to the write queue due to missing uri.`});
    }
  }
```

**Comment by rjrudin** [comment]
This is a fair point, particularly because I don't think there's much visibility to DH logging. 

Question though - was it a bug that the custom step was setting the URI to null? Or did the custom step intentionally not set a URI, and if so, for what purposes?

**Comment by rjrudin** [comment]
@josvanroosmalen  Closing this due to no response. Please open a JIRA ticket if this is still an issue for you, though note that I don't think we can introduce an error here due to backwards compatibility reasons - i.e. some users may be expecting an error not to be thrown because they've nulled out content.uri.
