### ISSUE TITLE
Inheritance?

### ISSUE THREAD

**Issue by ken-tune** [marklogic/marklogic-data-hub#392]
When creating flows default behavior is available.

I think it would be useful to customize this however.

Standard ( but project specific ) headers seem like the most obvious need. The next would be standard ( though different to current default ) writer code.

So my feature request is to build in customizable defaults.

In the absence of this, people need to remember to do the same thing every time when writing a flow, contradicting DRY.

**Comment by paxtonhare** [comment]
@ken-tune We actually encourage DRY coding. The way to do this is:

/plugins/
  ... anything under plugins gets deployed.

So you make library modules with the reusable code under /plugins/

Then you import them in your plugins and use them.

Make sense?

I realize we need to do a better job documenting this. Maybe if we had some default libraries that shipped with the DHF you would always see it there and know it's possible.

**Comment by ken-tune** [comment]
Hi Paxton

So I get that I can write libraries and use those library calls in my
header/content/writer etc.xqy by putting content under plugins/lib or
wherever.

I guess my point is that it would be useful if the *default* flows
generated by hubCreateInput/HarmonizeFlow could potentially be modified
so's the developer didn't have to remember to add the default behaviour.

Ken

**Comment by damonfeldman** [comment]
Any thoughts on what the defaults might be that we put into headers? A few I can think of are

Raw data header in the envelope
* ingest date for raw data
* data source (I think there is already a collection indicating the flow/entity, so that may be enough)
* Batch data - if we create a high-level notion of a "batch" with a batch identifier, we would track that with the raw data, perhaps also the harmonize batch

Harmonized/final header
* URIs of source docs incorporated into the final doc
* Harmonize date/time

What else might go into the standard header?

**Comment by ken-tune** [comment]
Damon

The above look like sensible suggestions.

I guess my point is that desired defaults will vary according to the
user/customer - so being able to set your own default header/triple/content
elements would be a useful addition. These would get populated when
hubCreateFlow is run.

Ken

**Comment by aebadirad** [comment]
Closing out old issue that no longer applies to the latest major release. Steps are now self-contained main modules and can inherit from any other module code.
