### ISSUE TITLE
[FEATURE] Make it easy to populate JSON null values

### ISSUE THREAD

**Issue by damonfeldman** [marklogic/marklogic-data-hub#3954]
**Is your feature request related to a problem? Please describe.**
Sometimes I want to capture a null value in my JSON, but the DHF mapping screen does not indicate how to do that, or have helper functions.

**What is the user-facing scenario that prompted this gap in functionality?**
We would like our records to distinguish between data from sources that do not have certain data (e.g. no AddressLine2) and data from sources where that data is present, but the particular record mapped did not have a value (raw data may have {ADDR_LINE2: ""}).

**Describe the solution you'd like**
Docs would help, but ideally a function such as mapEmptyAsNull(someRawField) where if the field is there but empty you get a null, if the field is populated you get the value, and if the field is missing it becomes missing in the FINAL doc.

**Describe alternatives you've considered**
use nodeBuilder.addNull() ind a custom .sjs function to return null.

**Additional context**
I don't think this is terribly high priority, but documenting here with "alternative" above as the workaround.

**Comment by rahulvudutala** [comment]
@damonfeldman Thank you for your feature request. Assigning it to @sbayatpur

**Comment by rjrudin** [comment]
@damonfeldman One idea - you have 3 outcomes:

1. There's no property to map
1. The property exists, but it does not have a value
1. The property exists, and it has a value

Currently, mapping is combining the first scenarios such that you can't distinguish which one actually occurred. 

But if we work from the right - is the goal to be able to query for records with a property that doesn't have a value, and/or view a record and see that it had the property but without a value? If so, what is the difference between a value of null/undefined/"" and a value of e.g. "NO_VALUE_FOUND", or "PROPERTY_EXISTS_BUT_NO_VALUE"?

And I'd argue that one of the latter choices is more self-describing than "", because a new developer 6 months will see it and immediately understand what scenario it represents. Whereas null/undefined/"" doesn't immediately imply that the property was found, but it didn't have a value.

Additionally, searching for records with a value of "PROPERTY_EXISTS_BUT_NO_VALUE" is trivial. 

This could be achieved with a mapping expression of e.g.

    (somePropertyName, "PROPERTY_EXISTS_BUT_NO_VALUE")[1]

So I'm basically lobbying for a clear indicator of the second scenario as opposed to an indicator - null/undefined/"" - that doesn't really describe the scenario.

**Comment by jmakeig** [comment]
For what it’s worth, my interpretation of `null` is what I understand `'PROPERTY_EXISTS_BUT_NO_VALUE'` means above, but with less ambiguity. `null` is also a valid JSON value, so I’d expect to be able to map to it regardless. Having to bust out `NodeBuilder` for this is not intuitive.

**Comment by rjrudin** [comment]
I think "PROPERTY_EXISTS_BUT_NO_VALUE" is not the right choice - I think the intent is to capture "The property existed from the source system, but no value was found". 

A value of null or undefined could originate for any number of reasons outside the mapping process. My understanding is that in this scenario, it's important to know that when the record was mapped, a property was found but without a value. That is more specific than just "null" existing. 

So maybe "SOURCE_PROPERTY_EXISTS_NO_VALUE"? I don't know. 

I think my main concern is that in the past, it's been confusing/difficult for newer ML developers to query for records that have an element/property with no value. Whereas it's trivial to query for a value that exists, everyone knows how to do that.

**Comment by jmakeig** [comment]
What do you mean “query for records that have an element/property with no value”? It’s not efficient in MarkLogic to query for documents that are _missing_ a property completely, but matching properties that have a `null` value works well with something like [`xdmp.jsonPropertyValueQuery`](https://docs.marklogic.com/10.0/cts.jsonPropertyValueQuery). Pardon the pun, but what am I missing here?

**Comment by rjrudin** [comment]
I did some testing, and if I make a custom mapping function that returns null, it still will not be included in the mapped instance. That's how the underlying mapper works. If we were to change that so that e.g. "myValue": null were added, we'd have a backwards compatibility issue for users that do not want "myValue" to be present when null is returned, regardless of what their mapping expression is. 

I think a step interceptor in 5.4.0 is the right solution here. That allows a user to choose to add "myValue":null when desired. Users that don't want that to happen don't need to do anything. 

If the demand for this is strong enough in the future - i.e. if we get enough requests about it - I could see an argument for DHF doing some post-processing of the instance returned by the mapper (as I don't think it's possible to change the mapper to handle null in a different manner).
