### ISSUE TITLE
How do we handle duplicates?

### ISSUE THREAD

**Issue by paxtonhare** [marklogic/marklogic-data-hub#438]
Not how do we find duplicates, but what do we do when we find them?

Do we merge them? Or do they live separately?

Looking for some best practices around this.

**Comment by jmakeig** [comment]
Duplicates of what? Entities?

**Comment by paxtonhare** [comment]
I think this was in the context of MDM.

Two documents come in representing the same person. one doc has Address A, the other has Address B. What to do?

The person who asked about this at MLWorld Chicago was looking for some guidance as to best practices. I'm thinking this is more use case dependent though.

**Comment by jmakeig** [comment]
Yes, I think matching, merging, and flagging for determination by a human will be something we need to tackle in the near future. We should eventually converge with what’s happening with [Agile Mastering ](http://www.marklogic.com/webinars/agile-mastering-new-approach-mdm/).

**Comment by damonfeldman** [comment]
Logically, Agile Mastering (the project) is perhaps an extension of the hub. It is nice to have it separately managed, however, with it's own release scheudle. It currently includes the hub, and can be used on a "data hub" that is built with bespoke code rather than the data hub framework, so that's another reason to keep it separate, but think of it as related.

**Comment by jmakeig** [comment]
> another reason to keep it separate

I think those boundaries are more meaningful to us than users (see [Conway](https://en.wikipedia.org/wiki/Conway%27s_law)). “I want to master as part of my integration. How do I do that?”
