### ISSUE TITLE
When deploying temporal collection data-hub uses data-capture-hub-content as the default

### ISSUE THREAD

**Issue by venuiyengar** [marklogic/marklogic-data-hub#443]
#### The issue
The gradle task deployTemporalCollections by defualt uses the data-capture-hub-content as the default instead of the one defined as part of the task

What behavior are you expecting?

Deploy fails with the error:

Executing command [com.marklogic.appdeployer.command.temporal.DeployTemporalCollectionsCommand] with sort order [751]
Processing files in directory: C:\Users\Iyengav1\dch\user-config\temporal\collections
Processing file: C:\Users\Iyengav1\dch\user-config\temporal\collections\dchTemporal.json
[mypotput.txt](https://github.com/marklogic/marklogic-data-hub/files/1086280/mypotput.txt)

Sending XML GET request as user 'admin' to path: /manage/v2/databases/data-capture-hub-content/temporal/collections
Logging HTTP response body to assist with debugging: <error xmlns="http://marklogic.com/xdmp/error">
  <status-code>404</status-code>
  <status>Not Found</status>
  <message-code>XDMP-NOSUCHDB</message-code>
  <message>XDMP-NOSUCHDB: xdmp:database("data-capture-hub-content") -- No such database data-capture-hub-content</message>
</error>

#### Tech details

Which Operating System are you using? Windows

Which version of MarkLogic are you using? 9.0

Which version of the Data Hub Framework are you using? 1.1.3

Is this a QuickStart UI bug? If so, which browser are you using? gradle Command line

#### The devil is in the details...

If possible, rerun the command with -d for debugging output and attach the output:

  **for quickstart:**  
  `java -jar quickstart.war -d > myoutput.txt`

  **for gradle:**  
  `gradle mlYourCommand -d > myoutput.txt`

**Comment by paxtonhare** [comment]
@rjrudin would like your opinion on this.

The problem for the DHF is that many of the AppDeployer commands are doing this:

```java
String dbName = databaseIdOrName != null ? databaseIdOrName : context.getAppConfig().getContentDatabaseName();
```

This works great in a setup with only 1 content database. For DHF I really need to give the developer a way to choose which database (staging|final) to put stuff. The fun complication is that, for any given asset, you might want it to go to either of the two.

I'm wondering if we should consider something like what you did with the collections and properties files; specify a .properties file that makes the decision.

**Comment by rjrudin** [comment]
@paxtonhare Does the developer make this decision while defining the resource, such that a properties file would work, or does the developer make the decision when running the Gradle task? 

I'm guessing the former, and I'm thinking the flaw is in the lack of a directory under e.g. "temporal" or "view-schemas" that defines the name of the database to deploy the resources to. Adding that directory makes sense because it solves this problem and maps nicely to the REST endpoint too. 

So instead of:

    /temporal/axis/temporal-system-axis.json

We'd have

    /temporal/my-database/axis/temporal-system-axis.json

This would be the first time that there's a change in where resources are defined for ml-app-deployer. Actually, it wouldn't need to be a change... ml-app-deployer could say "For the directories named 'axis' and 'collections', I'll assume that I use the default content database; for any other directory, I'll assume the directory name is a database name and I'll look for 'axis' and 'collections' under that directory."

**Comment by paxtonhare** [comment]
I like this approach.  Ideally this would work for any of the Commands that
make this assumption. There are several.

Should I file an issue with mlappdeloyer?

**Comment by rjrudin** [comment]
Yes, new issue in ml-app-deployer

**Comment by grechaw** [comment]
This issue was addressed in ml-app-deployer.  Maybe adding coverage for temporal collections is what would be required to verify this issue here.

**Comment by aebadirad** [comment]
This should work out of the box for DHF now since we've adopted vanilla ml-gradle deployment/config for the final app server. :) 

If it's not, or somehow needs enhancement, please open the issue.
