### ISSUE TITLE
[DOC] Documentation not clear about the meaning of sec/sec

### ISSUE THREAD

**Issue by coignetp** [marklogic/marklogic-data-hub#4552]
Hi everyone,

I'm trying to understand the meaning of the unit `sec/sec` of some load metrics, like `query-read-load` at `/manage/v2/forests?view=status` (https://docs.marklogic.com/REST/GET/manage/v2/forests@view=status).

This endpoint documentation states
> Disk reading time threads spent for a query in proportion to the elapsed time. This is a moving average summed for all of the contributing threads.

But the dashboards [documentation](https://docs.marklogic.com/guide/monitoring/dashboard#id_18325) states
> Loads -- The execution time (in seconds) of current read and write requests, which includes the time requests spend in the wait queue when maximum throughput is achieved.

And the dashboards shows metrics in `sec/sec`.

What's the exact meaning of this unit?

**Comment by rjrudin** [comment]
@coignetp  Apologize for the delay. This isn't a DHF question but an ML question, and what I could find as a description was this example:

"If a transaction holds 2 locks, then 
the time that each is held is added up. Conceivably, you could have a 
transaction that takes a lock, grinds away for several minutes of 
processing, and then takes a second lock. In this case, you'd have 1 
sec/sec during the grind since you hold one lock, and if you hold the 
second lock for a while you'd go up to 2 sec/sec."

I am closing this based on the fact that the referenced PR is closed as well, and hoping the above explanation suffices.
