### ISSUE TITLE
[BUG] Nested entity subfolders aren't detected when running hubGenerateTDETemplates

### ISSUE THREAD

**Issue by ahwitz** [marklogic/marklogic-data-hub#4817]
> Short description of the problem:

Nested folders under the `/entity` directory get pulled into the -SCHEMAS database correctly, but aren't recognized by the Gradle function to automatically generate TDEs off entities.

> What behavior are you expecting?

All files under `/entities/` should be pulled in to both.

> What are the steps to reproduce the issue:
1) Make a subfolder under `/entities/`
2) Put a valid entity file in there
3) Run `gradle hubDeployUserArtifacts` and validate that the entity file was correctly loaded into the SCHEMAS database
4) Run `hubGenerateTDETemplates` and note that a) the entity is not in the "About to generate a template for..." list and b) no TDE file is created
5) Bump the entity file up a level, re-run `hubGenerateTDETemplates` and note that the entity gets a TDE created

#### Tech details

> Which Operating System are you using?

CentOS 7, inside Docker

> Which version of MarkLogic are you using?

10.0-5

> Which version of the Data Hub are you using?

5.2.2

> Is this a QuickStart UI bug? If so, which browser are you using?

n/a

**Comment by rjrudin** [comment]
@ahwitz Apologize for the delay - I believe that the behavior of loading entities from a subfolder is unintentional (I think it was accidentally carried over from how DHF 4 works, where entity files were several folders deep), and DHF doesn't fully support it, as you've realized. 

I did a quick test, and the subfolder name is removed from the URI of the entity model. That further confirms that I don't think support for subfolders is intentional.

Do you have a use case for using a subfolder? Otherwise, we're going to treat this as a bug and fix DHF so that it does not try to load from subfolders, as it's confusing that it does do that given that it's not fully supported.

**Comment by ahwitz** [comment]
I think at that time, we were just trying to clean up the folder for when developers were having to scroll through 100+ entities. We've since slimmed that down and no longer have that kind of volume, but I can't personally think of any other use case.

**Comment by rjrudin** [comment]
@ahwitz Just following up, we're treating the fact that DHF does loading entities from ./entities/(subfolder) as a bug, since DHF clearly doesn't support it other than loading them. And that's confusing, since if they're loaded, you would think they'd be fully supported. 

So all entities will need to under ./entities, which is consistent with flows too. 

Let me know if you see a use case for ./entities/(some folder) though; if we get enough demand for it, we'd of course want to properly support it.

**Comment by ahwitz** [comment]
Totally fine. Only use case I can personally think of was the "cleaning up" thing I was talking about before, but we've since moved away from that anyway, so we've only got the one-level setup.

**Comment by rjrudin** [comment]
Tracking via DHFPROD-7015

**Comment by kkanthet** [comment]
Fixed in Data HUb 5.4.3
