### ISSUE TITLE
[BUG] mlLoadModules deploys options file to undesired app server

### ISSUE THREAD

**Issue by eaolson** [marklogic/marklogic-data-hub#4852]
This is a weird mishmash of ml-gradle, marklogic-data-hub, and marklogic-unit-test. I don't know the best place to report this, but it seems most relevant to DHF, so I'm trying here.

I'm using DHF 5, so my project has a data-hub-final and a data-hub-staging database and a REST endpoint for each. I have an options file that is used only for the data-hub-final database, which has a values constraint with an aggregate. The data-hub-final database has a path range index to support that aggregate. In my gradle.properties file, I have an **`mlStagingPort`** and **`mlFinalPort`** defined, but no **`mlRestPort`**, because until now I didn't know that was a thing.

Now I'm trying to set up marklogic-unit-test to work in this project. I think I have that working, using rjrudin's [instructions](https://gist.github.com/rjrudin/0dd97eaee16b1f8dc75a35c7acf7b4e1). Deploying the test resources creates a database and app server for data-hub-staging-test and data-hub-staging-final, similar to their non-test counterparts.

I have **`mlTestRestPort`** pointed to data-hub-staging-test in gradle.properties. Without that, `mlUnitTest` runs my tests on the data-hub-final port. I have no idea how it selects that, but it's not what I want.

Here's my problem: now when I run `mlLoadModules`, I get an error:

    RESTAPI-INVALIDCONTENT: (err:FOER0000) Invalid content: Operation results in invalid Options: 
    Aggregate "count" cannot be resolved on the specified index (check configuration, name, type).

The problem seems to be that my options file is being automatically deployed to `mlTestRestPort`, where it doesn't work, because there's no path range index in the data-hub-staging-test database.

The only solution I can think of is to point `mlTestRestPoint` at data-hub-final-test, which is not exactly what I want. I can probably work with it or call the unit tests from the port of the exact server I want.

I guess the underlying issue here is that ml-gradle loads modules assuming a one-database pattern, DHF uses a two-database pattern and there's no way to specify that an options file is for one database and not the other.

This is MarkLogic 10, DHF 5.2.3, marklogic-unit-test 1.0.0,

**Comment by rjrudin** [comment]
mlRestPort and mlTestRestPort are ml-gradle properties. If mlTestRestPort is set, then when modules are loaded, your search options will be loaded via the app server specified by mlTestRestPort. This is done so that search options are available via the test REST server, thus allowing them to be tested. ml-gradle isn't assuming a one-database pattern; it's assuming that you want your search options loaded via the test REST server so that you can test them. 

In your scenario though, since mlTestRestPort is set to an app server that points at a copy of your staging database, and that database doesn't have the given path range index, loading modules fails because the search options are loaded via mlTestRestPort. 

I think the right workaround here is shown in the unit-test example project in ml-gradle - https://github.com/marklogic-community/ml-gradle/tree/master/examples/unit-test-project - you can customize the databaseClientConfig object on the mlUnitTest task. That means you should not set mlTestRestPort, which will avoid the problem. 

Please reopen if that doesn't work.

**Comment by eaolson** [comment]
That worked for me. Thanks for the suggestion.
