### ISSUE TITLE
Harmonization design dilemma

### ISSUE THREAD

**Issue by ravi-b-m** [marklogic/marklogic-data-hub#521]
When my documents come into ML database, I have a `CPF` task which enhances the document by passing  the document through a series of pipelines (xquery libs), some of which call out to external REST based WS.

We are planning to move to `data-hub` framework, and here is my dilemma.
-  Do I do the document enrichment in my `harmonize` flow ? The enrichment process sometimes might take a while,  is this a good idea
- Do I still have the old `CPF` way of doing stuff, but the `cpf` task is after the harmonization flow ?

What are the best practices for having to do with harmonization flow ?

**Comment by paxtonhare** [comment]
@ravi-b-m It sounds like you are asking if you should rewrite significant portions of your application to use the harmonization flows. I'm not sure I would recommend that if it's already working.

The DHF doesn't make use of CPF because CPF is somewhat complicated to configure. We aim for simplicity.

There's nothing stopping you from using CPF if you like though.

As for the enrichment taking a long time in a harmonize flow, you would want to make sure the timeout is set appropriately in the Server config to allow it to complete successfully.

**Comment by popzip** [comment]
This is an interesting question - but seems resolved. @paxtonhare was there a thought to add this to documentation/FAQ somewhere, or can it be closed?

**Comment by aebadirad** [comment]
Closing this because we have an example of using database triggers to have an input flow trigger a harmonization flow (which could also be used for a cpf pipeline, if you should choose to go that way).
