### ISSUE TITLE
Allow having multiple custom hooks in a single step [FEATURE]

### ISSUE THREAD

**Issue by plackowk** [marklogic/marklogic-data-hub#5577]
**What gap would you like Data Hub Framework to address?**

Custom hooks can be evaluated either before processing content or after and this behavior can be set with "runBefore" flag set to true or false, respectively.
Currently, a step can only have zero or one custom hooks, so it's not possible to evaluate something "before" processing content  and something "after" processing content. I can't find a reason for this behavior.

**Describe the solution you'd like**

Allow a step to have multiple custom hooks, which could be declared in a following way:
```
"customHooks" : [
        {
            "module" : "/dhf5-custom-modules/lib/logExecutionSummary.xqy",
            "parameters" : {},
            "runBefore" : true
        },
        {
            "module" : "/dhf5-custom-modules/lib/evaluate-writer-custom-hook.xqy",
            "parameters" : {},
            "runBefore" : false
        }
    ]
```

**Comment by rjrudin** [comment]
In 5.4, you can use an interceptor for the "after" part. We intend to support interceptors during other events in the execution of a step as well. 

In the meantime, I think you can do a "before" custom hook and an interceptor. I'm wondering though if a custom - which runs in a separate update transaction - is actually what you want; I'm assuming you'd rather use interceptors (which run in the same transaction) for both before/after.

**Comment by plackowk** [comment]
Yes, seems like custom hook "before" + interceptor with `"when" : "beforeContentPersisted"` will work for me.

There is no documentation about interceptors though. And from what I see in the code, interceptors can only mimic (despite transaction differences) custom hooks "after" as "beforeContentPersisted" is the only valid value for "when" key:
```
      "interceptors": [
        {
          "path": "/custom-modules/step-interceptors/onIngest.sjs",
          "when": "beforeContentPersisted"
        }
      ]
```
How can I configure an interceptor for "before" kind custom hook?

**Comment by rjrudin** [comment]
See https://docs.marklogic.com/datahub/5.4/flows/about-interceptors-custom-hooks.html for docs, which also links to a working example project. "before" interceptors aren't supported yet, but we intend to do so.

**Comment by plackowk** [comment]
I've just come to a problem, where I need "before" and "after" custom-hooks in the same step. I need to evaluate something before a step (I could use "before" interceptor here, if they existed), and after a step I need to gather execution information about the current step from jobs-database. The second has to be done as custom-hook, because if it's replaced by interceptor, I'm getting a not-yet-updated execution info.

**Comment by plackowk** [comment]
Actually, what's that hard about implementing "before" interceptors. I think I know how to do it. Should I make my own PR to datahub project?

**Comment by rjrudin** [comment]
We'll be adding "before" interceptors for 5.5. Additionally, 5.5 is introducing a beforeMain function that a step module can implement, although that will only matter for a custom step, where interceptors typically don't matter as much. 

For your use case above - where you want to "gather execution information from the current step from the jobs database" - what data are you looking to get exactly - i.e. are you getting Job, Batch, or provenance documents from the jobs database?

**Comment by rjrudin** [comment]
For internal folks, ticket is DHFPROD-7292

**Comment by plackowk** [comment]
I need to extract most of data from such single step, after the step is completed:
```
            "1":{
                "flowName:"%%confidential%%",
                "stepName:"%%confidential%%",
                "stepDefinitionName:"%%confidential%%",
                "stepDefinitionType":"ingestion",
                "targetEntityType":null,
                "targetDatabase:"%%confidential%%",
                "stepOutput":null,
                "fullOutput":null,
                "status":"completed step 1",
                "totalEvents":150,
                "successfulEvents":150,
                "failedEvents":0,
                "successfulBatches":2,
                "failedBatches":0,
                "success":true,
                "stepStartTime":"2021-04-27T16:24:41.611157Z",
                "stepEndTime":"2021-04-27T16:24:57.481436Z"
            },
```
Particularly I need to know stepEndTime, successfulEvents and failedEvents, because from this data I will create a document, which I will use to calculate something at the beginning of the next step.

**Comment by rjrudin** [comment]
If your "when" is "when the step has completed", I don't think a custom hook is what you want, since that will fire for every batch that is processed by a step, and a batch doesn't know if it's the "last" one or not. The data you listed above is in the Job document, which isn't updated until all batches have been processed for a step. 

I think for your use case, you can insert a custom step in between the step we're talking about and the next step. That custom step can have a sourceQuery that is limited to one item - i.e. it can be a cts.documentQuery on itself. And then the step module for that custom step can peer into the jobs database and find the data it needs and then return a single content object to be written, which your next step depends on. 

I'm also wondering if a new feature in 5.5 will help you - that feature will allow you to run multiple steps in one call to ML, either via a new REST extension or via the DHF transform for MLCP. Instead of a sourceQuery being used for each step, the output of one step becomes the input to the next step, so there is a true "flow" to the data being processed. 

The use case - which we've received a lot of requests to support - is when new data is ingested into ML (often from an external system like Kafka/NiFi/Spark/etc), the user wants to e.g. map/match/merge it as part of ingesting it into ML. DHF's batch-oriented flows don't support that today, which is why we're adding this new feature. Wondering if that might be applicable for your use case, as you wouldn't have to resort to hooks/interceptors at all.

**Comment by plackowk** [comment]
You are absolutely right. Thanks for idea about custom between-in step! That will make it.

**Comment by rjrudin** [comment]
Do you mind if I close this ticket, as we not going to make any further changes to custom hooks, and we will be supporting a "start" interceptor (name of "when" is TBD, but will be something like "start" or "atStart") in 5.5.0?

**Comment by plackowk** [comment]
I don't mind, but could you provide me some contact email if I have more questions related to DHF?
