### ISSUE TITLE
Transforms in XQuery to run the flow in update mode

### ISSUE THREAD

**Issue by vivekmuniyandi** [marklogic/marklogic-data-hub#569]
Right now the transforms in Xquery runs only in query mode. I am using ApplyTransformListener to run the flow which runs in update mode. Hence it would be nice if we have it run in both query and update mode.

**Comment by paxtonhare** [comment]
@vivekmuniyandi one of the important things we do with the DHF is to give you guardrails for safety. As such, we insist that you run your flows in query-only mode so that you don't lock too many documents.

I won't be able to let you run in update-mode. But I can modify the transform to eval the code so that it does run in query mode.

**Comment by vivekmuniyandi** [comment]
Sure that would be great. thanks.

**Comment by jmakeig** [comment]
Transforms are not updates because they don’t actually hit the database. (Is that correct, @paxtonhare?) They’re like calling a pure function: you give it input, the transform gives you output. What you do with that output is up to you. Persisting the result of the transformation is a separate concern. 

Why then to you need to run a transformation in update mode, @vivekmuniyandi? Having side-effects in transformations (other than logging/tracing) sounds like a very slippery slope and a great way to get in trouble with unanticipated locks, as @paxtonhare indicates.

**Comment by vivekmuniyandi** [comment]
@jmakeig I was using ApplyTransformListener to have the input flow run for documents already in the staging database. Since we had to process docx, pdf files via Content Processing Framework, we had to ingest those documents into Marklogic for the content to be processed. Then instead of creating new envelope documents on top of the already ingested and processed documents, I thought of replacing it using the ApplyTransformListener which has the default characteristic of replacing the documents. 

Now, we have decided to not replace but keep the processed documents as such and create new envelopes and not replacing it.

**Comment by damonfeldman** [comment]
@jmakeig - pretty much. A "harmonize" flow conceptually does some transforms and then writes the resulting record, which is an envelope-pattern document with sections that are all conceptually transforms. the header plugin "transforms" content into the desired headers. the triples plugin "transforms" the content into useful triples, and the content transform is a more traditional transform because it replaces the raw content with the new (harmonized/final) content.

For safety as Paxton says, the hub does all the transforms in read mode, since people tend to query and join data when doing transforms, and we don't want to lock all that stuff in update mode.

Of course the final plugin for the harmonize flow is the writer, and *that* runs in update mode.

**Comment by jmakeig** [comment]
> Now, we have decided to not replace but keep the processed documents as such and create new envelopes and not replacing it.

Does that mean you don’t need the ability to run transform in update mode? Where did we land?

**Comment by paxtonhare** [comment]
@jmakeig it's a side effect of the ApplyTransform code. Perhaps it's not intentional.. but the way that  code works is to run something like:

```xquery
let $result := run-user-transform()
return
  xdmp:node-replace($original, $result)
```

and because it is written this way it forces update mode of the user's transform.

**Comment by aebadirad** [comment]
Closing out old issue that no longer applies to the latest major release.
