### ISSUE TITLE
Deleting an entity deletes associated flows and code without warning or confirmation

### ISSUE THREAD

**Issue by damonfeldman** [marklogic/marklogic-data-hub#578]
Deleting an entity should have more warnings or safety. Could be an enhancement but I'll put this in as a bug.

### Hub Version
2.0

┆Status: Done

**Comment by mhuang-ml** [comment]
@dmcassel, @damonfeldman, and @popzip , I've added an additional modal dialog box so that the user will have to press "Yes" twice before we delete the entity and all associated flows and code.  Are there specific checks that we would want to perform?  I've made the changes to the current "develop" branch, should this change be made to the 1.0 and 2.0 branches as well?

Here's the original dialog message that is currently in the develop branch that I'm leaving unchanged:
![initialyesdialog_unchanged](https://user-images.githubusercontent.com/16652599/38780637-e68afeea-40a7-11e8-996a-3530b1f4ed8a.png)

When a user presses the "Yes" button, then the new dialog box will appear like the following:
![additionaldialogmessage](https://user-images.githubusercontent.com/16652599/38780653-25b223c8-40a8-11e8-9b86-1ec5b3096618.png)

If the user presses "Yes" to the new dialog box, then it will proceed with deleting the entity and all associated flows and code.  If the user presses "No" to the second modal window, then it will **NOT** delete anything.

I just wanted to double check this implementation to make sure I'm not missing anything within the scope of this ticket.

**Comment by mhuang-ml** [comment]
@grechaw, thank you for the clarification for the changes coming up in the 3.0 branch.  Is the plan that 1.0 and 2.0 would have the entities and flows separated as well?  I'm trying to wrap my head around if there is any portion of this task that can be done now in terms of a warning/confirmation, or will all of this become moot with the future changes?

**Comment by grechaw** [comment]
We're not likely to go back to 2 or 1 to separate the flows -- all our work is in the 3 branch now.

**Comment by mhuang-ml** [comment]
@grechaw, thanks for the updates.  So it seems like I can scrap the code for the 3.0/develop branch then since these are going to be split out during the summer.  Is there value in me adding the additional dialogs to the 1.0/2.0 branches now since the flows aren't going to be separated in the future?  Or I can scrap this code altogether and leave this ticket in the backlog so that it can be addressed when the entities and flows are split out.

**Comment by grechaw** [comment]
I'd like to leave this bug open until it's resolved.  As for 2 branch, a dialog might be a good response.  Feel free to submit a PR, we can look at doing a 2.0 branch maintenance release if product team feels its a good idea.

We do think that migrating to 3.0 will make you happier though.

**Comment by mhuang-ml** [comment]
Great thanks again @grechaw!  I'll create a PR for the 2.0 develop branch.  Thanks again for all of your input!

**Comment by popzip** [comment]
If the code is written its not a bad idea to add to 3.1 is it?

**Comment by aebadirad** [comment]
Yeah, let's slot it for 3.1 as well to cover the gap before we split out entities/flows.

**Comment by dmcassel** [comment]
➤ Scott Brooks commented:

Code change handled by Michael Huang
[~mhuang] in PR [https://github.com/marklogic/marklogic-data-hub/commit/e5e7512f14bd5546965c66aac92cb7e9282a429e](https://github.com/marklogic/marklogic-data-hub/commit/e5e7512f14bd5546965c66aac92cb7e9282a429e)

Setting status to In Review

**Comment by dmcassel** [comment]
➤ Charles Greer commented:

This is in a PR from the community

**Comment by dmcassel** [comment]
➤ Scott Brooks commented:

I went ahead and created the PR for the develop branch with your fix [@mhuang-ml](https://github.com/mhuang-ml).  See:  [https://github.com/marklogic/marklogic-data-hub/pull/917](https://github.com/marklogic/marklogic-data-hub/pull/917)

**Comment by dmcassel** [comment]
➤ Scott Brooks commented:

Video capturing change:  [https://drive.google.com/file/d/155e9TfhcWecL1yrNN5-8umEctsPUFa8L/view](https://drive.google.com/file/d/155e9TfhcWecL1yrNN5-8umEctsPUFa8L/view)

**Comment by dmcassel** [comment]
➤ Scott Brooks commented:

Change merged into develop branch.  Passing to QA.

**Comment by wooldridge** [comment]
Sorry I’m late to the party here. I don’t think we need to double up on the confirmation dialog boxes. I think adding clearer messaging to the existing dialog about what all is deleted along with the entity is sufficient.

I also think we don’t need to say “code,” if by code we mean plugins, since the plugins are simply the building blocks of the flows. (I may be wrong. Maybe there is additional important "code" that goes away, in which case we should say what.)

——————
Delete the Product entity?

Any flows associated with the 
entity will also be deleted.

NO   YES
——————

**Comment by ayuwono** [comment]
I agree with Mike's suggestion. Two dialog boxes are redundant
