### ISSUE TITLE
Copying file into plugins/** dir does not fire the autodeploy

### ISSUE THREAD

**Issue by paxtonhare** [marklogic/marklogic-data-hub#769]
for whatever reason copy/paste a file into the plugins/** dir won't trigger a code deploy.

**Comment by aebadirad** [comment]
Copy and paste preserves the modified date by default, which is what mlwatch uses to determine if something needs to be triggered on.

This is an ml-gradle issue, so going to close this out, because any changes to 'correct' this behavior are outside the scope of the issue and would be addressed either by ml-gradle or a redesign of how deployments would work in DHF 4.x.
