### ISSUE TITLE
Better support for relational sources

### ISSUE THREAD

**Issue by paxtonhare** [marklogic/marklogic-data-hub#78]
As a developer, I want to be able to more easily integrate data from relational sources. 

* Denormalize tables into entities as entities, including left-joined lookup values
* Bulk or trickle export (throttle, pool, cache)
* Capture DDL metadata to document provenance and to assist in mapping to canonical forms
* Change data capture (#367)

┆Status: New

**Comment by bobstarbird** [comment]
I modified ml-migration-starter to prototype support for relational sources:
Changed MigrationConfig to use a ServerTransform. Created a new transform to map calling conventions from ml-java-client-api document write to datahub mlcp-flow-transform.
Changed AllTablesItemReader to add support for MetaData lookup of key; add columns to select for RDBMSName, TableName, and Key; support multivendor QuotedIdentifiers.
Changed ColumnMapProcessor to write three part URI (RDBMSName, TableName, key).

Created additional code to transform table defintions into EntityServices models and upload and create TDE SQL views.

**Comment by popzip** [comment]
@bobstarbird Is this on a personal fork?
cc @jmakeig @sammefford who might be interested in this conversation/effort

**Comment by sammefford** [comment]
That's great to hear @bobstarbird , I'm interested to hear more.  ml-migration-starter was my first thought on reading this issue summary just now.  Actually, [multiline-ml-migration-starter](https://github.com/rjrudin/ml-multiline-record-ingest-starter) since it starts to address the issue of joins creating cross-join / cartesian product noise.   Please also note that I've written up some thoughts on [how to do CDC](https://wiki.marklogic.com/x/RpjqAw).  I'd love your feedback on that.

**Comment by grechaw** [comment]
Converted to story in jira, closing here in github. 

https://project.marklogic.com/jira/browse/DHFPROD-530
