### ISSUE TITLE
Refactor how site docs are produced

### ISSUE THREAD

**Issue by popzip** [marklogic/marklogic-data-hub#810]
As a data hub user, I need to access DHF documentation even when offline/without internet.

As part of data hub product team, I need to review in progress DHF documentation (that is not yet live with master branch) without building myself. (non-master/released copies).

**Comment by wooldridge** [comment]
We may want to investigate other static site generators (we currently use Ruby-based [Jekyll](https://jekyllrb.com/)) that will make it easier to do the above but also continue to integrate with GitHub Pages (which we currently use to serve our docs).

One such option is DocPad, which is based on Node.js instead of Ruby:

http://docpad.org/docs/intro/

**Comment by aebadirad** [comment]
This was completed. Docs now exist at http://docs.marklogic.com/datahub/
