### ISSUE TITLE
RFE: Single location for all resource configuration

### ISSUE THREAD

**Issue by tternquist** [marklogic/marklogic-data-hub#873]
#### The issue
Currently there is a split between internal-hub-config and user-config for resource configuration. This can be confusing as applications will almost certainly need to modify internal-hub-config to create range indexes on the built-in databases. 

My opinion is DHF should follow the same conventions as vanilla ml-gradle and not have this split. Related to #872 and #666

**Comment by grechaw** [comment]
I like this idea too.   Points to a kind of overhaul of DHF config in general.

**Comment by iowusu** [comment]
I agree to this. I came across this and it can be confusing. Using the same standards at vanilla-gradle will simplify maintenance

**Comment by grechaw** [comment]
Hi @iowusu and @tternquist I think the 4.0.0 release addresses exactly this concern.  There's still a little complexity because of how the appservers interact.  I'm going to close out this issue, as we're trying to clear out issues we believe to be fixed in 4.0.0.  I could of course be wrong as I'm using a broad brush.
