### ISSUE TITLE
Content plugin shows incorrect Input and Output

### ISSUE THREAD

**Issue by sbuxton** [marklogic/marklogic-data-hub#895]
#### The issue

In the DHF Tutorial 2.x , 
Traces -> flow type = Input -> first document
select Content plugin

You see "raw content" and "output".
They look just like the image at the bottom of
https://marklogic-community.github.io/marklogic-data-hub/tutorial/load-products-as-is/

Both "raw content" and "output" show a source JSON document.
But that raw JSON document doesn't exist in the database anywhere.
In fact, the input to this flow is a CSV file (not JSON at all), and the output is an envelope document.

#### Tech details

Which Operating System are you using?
Linux
Which version of MarkLogic are you using?

Which version of the Data Hub Framework are you using?
2.x
Is this a QuickStart UI bug? If so, which browser are you using?
No.

**Comment by wooldridge** [comment]
I suspect this is not a bug. We're displaying what is input to and output from the content plugin, not the entire input flow. By the time the input arrives to the content plugin, that CSV row has been turned into a JSON document. And since the content plugin in this example is just passing it through, the input and output are the same (and the output is not yet a full envelope document).

What's seen in the UI is consistent with what's seen in the Tracing database.

@aebadirad can likely confirm.

This could be made clearer in the documentation as the term "rawContent" here is confusing.

**Comment by aebadirad** [comment]
We always wrap in an envelope by default, unless the user takes steps to truly 'load as is'.
