### ISSUE TITLE
Detect (vet) bad user plugins

### ISSUE THREAD

**Issue by paxtonhare** [marklogic/marklogic-data-hub#91]
Similar to how app services detects when a transform is bad, we should static check user plugins before or during installing.

**Comment by maeisabelle** [comment]
Hi @paxtonhare,

I'm trying to implement this. I'm testing it first in Query Console using xdmp:eval with options "<static-check>true</static-check>". This is the one I'm executing in my Query Console:

xquery version "1.0-ml";

let $content := xdmp:filesystem-file("/Users/mturiana/marklogic-data-hub/quick-start/plugins/entities/Employee/input/IngestFlow/content/content.xqy")
let $updatedContent := fn:replace($content, 'module namespace plugin','declare namespace plugin')
let $query := concat($updatedContent,'success')
return
    xdmp:eval($query, (),
                   <options xmlns="xdmp:eval">
                       <database>{xdmp:database('data-hub-modules')}</database>
                       <static-check>true</static-check>
                   </options>)

It's doing the static check from my file system. But as you can see in my code, I'm replacing the "module namespace plugin" to "declare namespace plugin". This is because I'm getting an error "Cannot evaluate library module" if not. 

Is this ok to simulate in Java in data hub using ServerEvaluationCall.xquery (databaseClient.newServerEval().xquery(query).eval())? Or do you have a better suggestion?

Thanks!

**Comment by paxtonhare** [comment]
Mae, I have a pretty good understanding of this one. I'll just go ahead and take it.
